import os
import io
import re
import html
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from fpdf import FPDF

def sanitize_text(text: str) -> str:
    """Removes special characters and typographic quotes to ensure clean formatting."""
    replacements = {
        "\u2018": "'", "\u2019": "'",
        "\u201c": '"', "\u201d": '"',
        "\u2014": "-", "\u2013": "-",
        "\u2026": "..."
    }
    for orig, rep in replacements.items():
        text = text.replace(orig, rep)
    # Remove excessive consecutive empty newlines
    return re.sub(r"\n{3,}", "\n\n", text).strip()

def format_html_preview(text: str) -> str:
    """Converts raw output into stylized HTML blocks for inline display."""
    escaped = html.escape(text)
    # Highlight markdown-like bold headers
    escaped = re.sub(r"\*\*(.*?)\*\*", r"<strong>\1</strong>", escaped)
    formatted = escaped.replace("\n", "<br>")
    return (
        f"<div style='background-color: #1e1e1e; color: #f0f0f0; padding: 20px; "
        f"border-radius: 8px; max-height: 450px; overflow-y: auto; font-family: monospace; "
        f"line-height: 1.6; border: 1px solid #333;'>"
        f"{formatted}"
        f"</div>"
    )

def format_docx(text: str, doc_type: str, terms: str = "") -> io.BytesIO:
    """Formats raw legal text into a structured .docx with logo, headers, and a terms table."""
    doc = Document()
    
    # Optional header logo
    logo_path = os.path.join(os.path.dirname(__file__), "..", "Image", "Logo.png")
    if os.path.exists(logo_path):
        try:
            doc.add_picture(logo_path, width=Inches(1.5))
        except Exception:
            pass

    # Document Heading
    title = doc.add_heading(doc_type.upper(), level=0)
    title.runs[0].font.name = "Times New Roman"
    title.runs[0].font.size = Pt(18)
    title.runs[0].font.color.rgb = RGBColor(0, 51, 102)

    # Document Body
    for line in text.split("\n"):
        clean_line = line.strip()
        if not clean_line:
            continue
        p = doc.add_paragraph()
        run = p.add_run(clean_line)
        run.font.name = "Times New Roman"
        run.font.size = Pt(11)

    # Terms Table (if semicolon-separated terms are provided)
    if terms:
        term_items = [t.strip() for t in terms.split(";") if t.strip()]
        if term_items:
            doc.add_heading("Key Terms Summary", level=2)
            table = doc.add_table(rows=1, cols=2)
            table.style = "Table Grid"
            hdr_cells = table.rows[0].cells
            hdr_cells[0].text = "Clause #"
            hdr_cells[1].text = "Term Description"
            for i, term in enumerate(term_items, start=1):
                row_cells = table.add_row().cells
                row_cells[0].text = str(i)
                row_cells[1].text = term

    # Footer note
    footer = doc.sections[0].footer
    footer_para = footer.paragraphs[0]
    footer_para.text = "Generated by LegalEase AI | Confidential Legal Document"
    footer_para.runs[0].font.size = Pt(8)

    file_stream = io.BytesIO()
    doc.save(file_stream)
    file_stream.seek(0)
    return file_stream

class LegalPDF(FPDF):
    def header(self):
        logo_path = os.path.join(os.path.dirname(__file__), "..", "Image", "Logo.png")
        if os.path.exists(logo_path):
            try:
                self.image(logo_path, 10, 8, 25)
            except Exception:
                pass
        self.set_font("Helvetica", "B", 13)
        self.cell(0, 10, "LegalEase - Formal Document", ln=True, align="R")
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by LegalEase AI", align="C")

def format_pdf(text: str, doc_type: str) -> io.BytesIO:
    """Formats raw legal text into a branded PDF with header/footer."""
    pdf = LegalPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    
    pdf.set_font("Helvetica", "B", 15)
    pdf.cell(0, 10, doc_type.upper(), ln=True, align="C")
    pdf.ln(5)

    pdf.set_font("Helvetica", size=10)
    for line in text.split("\n"):
        clean_line = line.strip()
        safe_line = clean_line.encode("latin-1", "replace").decode("latin-1")
        pdf.multi_cell(0, 6, safe_line)
        pdf.ln(1)

    pdf_output = pdf.output(dest='S')
    pdf_bytes = pdf_output.encode("latin-1") if isinstance(pdf_output, str) else bytes(pdf_output)

    file_stream = io.BytesIO(pdf_bytes)
    file_stream.seek(0)
    return file_stream